### ISSUE TITLE
5.4.7那个内核装上去了，但是没有bbrplus

### ISSUE THREAD

**Issue by ghost** [ylx2016/kernel#1]
我先安装了header和image，重启后uname -a，显示内核已经启用。开启bbrplus失败，提示

sysctl: setting key "net.ipv4.tcp_congestion_control": No such file or directory

net.ipv4.tcp_available_congestion_control为reno cubic bbr。

然后我把libc-dev装上，bbr也消失了

**Comment by ylx2016** [comment]
你都没说你什么版本系统

kirin10000 <notifications@github.com>于2020年1月28日 周二下午11:42写道：

**Comment by ylx2016** [comment]
5.4.7 我并没有提到有bbrplus
只有4.14的内核才有bbrplus  谢谢
如果其他版本需要bbrplus 你要想csdn的作者要更改的算法 见README.md
