### ISSUE TITLE
Ubuntu 6.0.2 arm64出错

### ISSUE THREAD

**Issue by IATA2024** [ylx2016/kernel#10]
oracle arm的debian 11机器，安装Ubuntu_Kernel_6.0.2_latest_arm64_bbr_2022.10.16-0858时，运行卸载内核的脚本到以下命令后没有内核了：
Generating grub configuration file ...
Adding boot menu entry for EFI firmware configuration
done

**Comment by ylx2016** [comment]
action上传出错了，人工我重传了，测试有了，你重新运行下

**Comment by IATA2024** [comment]
成功了，多谢，辛苦了！
