### ISSUE TITLE
Debian_Kernel_6.2.2 没有image

### ISSUE THREAD

**Issue by BrunuhVille** [ylx2016/kernel#11]
Debian_Kernel_6.2.2_latest_bbr_2023.03.08-1503

没有linux-image

**Comment by ylx2016** [comment]
> Debian_Kernel_6.2.2_latest_bbr_2023.03.08-1503
> 
> 
> 
> 没有linux-image

晚点我手动传下，在外面，预计天黑前处理

**Comment by ylx2016** [comment]
done
