### ISSUE TITLE
5.13.0

### ISSUE THREAD

**Issue by IATA2024** [ylx2016/kernel#4]
arm64和bbrplus不再更新了吗？

**Comment by ylx2016** [comment]
5.13.0 plus是编译失败了 等5.13.1再看看 可能需要原作者适配 或者我留在5.12版本
arm64是我关了，怕不兼容，没去适配5.13，这个也得等5.13.1出来再看看

**Comment by ylx2016** [comment]
都处理好了 你有空可以测试下看看
bbrplus我调了下 
arm64也调了下

**Comment by IATA2024** [comment]
测试成功，多谢！
