### ISSUE TITLE
tcp.sh加速出现can't read /etc/sysctl.d/99-sysctl.conf

### ISSUE THREAD

**Issue by BrunuhVille** [ylx2016/kernel#6]
[](url)debian10系统
tcp.sh版本v1.3.2.91
bbr内核版本5.13.7
使用选项25. 卸载全部加速
![image](https://i.w3tt.com/2021/08/03/qE3fp.png)
会出现连续几十行的
sed: can't read /etc/sysctl.d/99-sysctl.conf: No such file or directory

**Comment by ylx2016** [comment]
忽略吧... 优化去掉了就行
新的方案是直接删除了文件了，然后老的方案还在所以就这样了
