### ISSUE TITLE
Ubuntu 5.15.4 arm64出错

### ISSUE THREAD

**Issue by IATA2024** [ylx2016/kernel#7]
oracle arm的debian 10机器，安装Ubuntu_Kernel_5.15.4_latest_arm64_bbr_2021.11.22-1626时，运行卸载内核的脚本到以下命令后没有内核了：
Generating grub configuration file ...
Adding boot menu entry for EFI firmware configuration
done

**Comment by ylx2016** [comment]
处理中,已经回滚5.15.1，新的5.15.4action重新编译中
编译的内核炸了

**Comment by ylx2016** [comment]
重新编译的又炸了 暂时不编译了 用5.15.1的吧
删除的时候布小心把5.15.4的AMD删了....
